#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f f1_auto.vcd

# run Verilator to translate Verilog intro C++, including C++ testbench
verilator -Wall --cc --trace f1_auto.sv --exe f1_auto_tb.cpp
verilator -Wall --cc --trace f1_fsm.sv
verilator -Wall --cc --trace clktick.sv

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1_auto.mk Vf1_auto

#run executable simulation file
obj_dir/Vf1_auto